/* tslint:disable */
/* eslint-disable */

// ######################################## THIS FILE WAS GENERATED BY MONGOOSE-TSGEN ######################################## //

// NOTE: ANY CHANGES MADE WILL BE OVERWRITTEN ON SUBSEQUENT EXECUTIONS OF MONGOOSE-TSGEN.

import mongoose from "mongoose";

/**
 * Lean version of CommentDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `CommentDocument.toObject()`. To avoid conflicts with model names, use the type alias `CommentObject`.
 * ```
 * const commentObject = comment.toObject();
 * ```
 */
export type Comment = {
  content: string;
  video: Video["_id"] | Video;
  owner: User["_id"] | User;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of CommentDocument (type alias of `Comment`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Comment } from "../models"
 * import { CommentObject } from "../interfaces/mongoose.gen.ts"
 *
 * const commentObject: CommentObject = comment.toObject();
 * ```
 */
export type CommentObject = Comment;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type CommentQuery = mongoose.Query<
  any,
  CommentDocument,
  CommentQueries
> &
  CommentQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `CommentSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type CommentQueries = {};

export type CommentMethods = {};

export type CommentStatics = {};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Comment = mongoose.model<CommentDocument, CommentModel>("Comment", CommentSchema);
 * ```
 */
export type CommentModel = mongoose.Model<CommentDocument, CommentQueries> &
  CommentStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new Comment schema instances:
 * ```
 * const CommentSchema: CommentSchema = new mongoose.Schema({ ... })
 * ```
 */
export type CommentSchema = mongoose.Schema<
  CommentDocument,
  CommentModel,
  CommentMethods,
  CommentQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Comment = mongoose.model<CommentDocument, CommentModel>("Comment", CommentSchema);
 * ```
 */
export type CommentDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  CommentQueries
> &
  CommentMethods & {
    content: string;
    video: VideoDocument["_id"] | VideoDocument;
    owner: UserDocument["_id"] | UserDocument;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of LikeDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `LikeDocument.toObject()`. To avoid conflicts with model names, use the type alias `LikeObject`.
 * ```
 * const likeObject = like.toObject();
 * ```
 */
export type Like = {
  likedBy: User["_id"] | User;
  video?: Video["_id"] | Video;
  comment?: Comment["_id"] | Comment;
  tweet?: Tweet["_id"] | Tweet;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of LikeDocument (type alias of `Like`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Like } from "../models"
 * import { LikeObject } from "../interfaces/mongoose.gen.ts"
 *
 * const likeObject: LikeObject = like.toObject();
 * ```
 */
export type LikeObject = Like;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type LikeQuery = mongoose.Query<any, LikeDocument, LikeQueries> &
  LikeQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `LikeSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type LikeQueries = {};

export type LikeMethods = {};

export type LikeStatics = {};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Like = mongoose.model<LikeDocument, LikeModel>("Like", LikeSchema);
 * ```
 */
export type LikeModel = mongoose.Model<LikeDocument, LikeQueries> & LikeStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new Like schema instances:
 * ```
 * const LikeSchema: LikeSchema = new mongoose.Schema({ ... })
 * ```
 */
export type LikeSchema = mongoose.Schema<
  LikeDocument,
  LikeModel,
  LikeMethods,
  LikeQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Like = mongoose.model<LikeDocument, LikeModel>("Like", LikeSchema);
 * ```
 */
export type LikeDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  LikeQueries
> &
  LikeMethods & {
    likedBy: UserDocument["_id"] | UserDocument;
    video?: VideoDocument["_id"] | VideoDocument;
    comment?: CommentDocument["_id"] | CommentDocument;
    tweet?: TweetDocument["_id"] | TweetDocument;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of PlaylistDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `PlaylistDocument.toObject()`. To avoid conflicts with model names, use the type alias `PlaylistObject`.
 * ```
 * const playlistObject = playlist.toObject();
 * ```
 */
export type Playlist = {
  name: string;
  description: string;
  videos: (Video["_id"] | Video)[];
  owner: User["_id"] | User;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of PlaylistDocument (type alias of `Playlist`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Playlist } from "../models"
 * import { PlaylistObject } from "../interfaces/mongoose.gen.ts"
 *
 * const playlistObject: PlaylistObject = playlist.toObject();
 * ```
 */
export type PlaylistObject = Playlist;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type PlaylistQuery = mongoose.Query<
  any,
  PlaylistDocument,
  PlaylistQueries
> &
  PlaylistQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `PlaylistSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type PlaylistQueries = {};

export type PlaylistMethods = {};

export type PlaylistStatics = {};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Playlist = mongoose.model<PlaylistDocument, PlaylistModel>("Playlist", PlaylistSchema);
 * ```
 */
export type PlaylistModel = mongoose.Model<PlaylistDocument, PlaylistQueries> &
  PlaylistStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new Playlist schema instances:
 * ```
 * const PlaylistSchema: PlaylistSchema = new mongoose.Schema({ ... })
 * ```
 */
export type PlaylistSchema = mongoose.Schema<
  PlaylistDocument,
  PlaylistModel,
  PlaylistMethods,
  PlaylistQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Playlist = mongoose.model<PlaylistDocument, PlaylistModel>("Playlist", PlaylistSchema);
 * ```
 */
export type PlaylistDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  PlaylistQueries
> &
  PlaylistMethods & {
    name: string;
    description: string;
    videos: mongoose.Types.Array<VideoDocument["_id"] | VideoDocument>;
    owner: UserDocument["_id"] | UserDocument;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of SubscriptionDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `SubscriptionDocument.toObject()`. To avoid conflicts with model names, use the type alias `SubscriptionObject`.
 * ```
 * const subscriptionObject = subscription.toObject();
 * ```
 */
export type Subscription = {
  subscriber: User["_id"] | User;
  channel: User["_id"] | User;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of SubscriptionDocument (type alias of `Subscription`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Subscription } from "../models"
 * import { SubscriptionObject } from "../interfaces/mongoose.gen.ts"
 *
 * const subscriptionObject: SubscriptionObject = subscription.toObject();
 * ```
 */
export type SubscriptionObject = Subscription;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type SubscriptionQuery = mongoose.Query<
  any,
  SubscriptionDocument,
  SubscriptionQueries
> &
  SubscriptionQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `SubscriptionSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type SubscriptionQueries = {};

export type SubscriptionMethods = {};

export type SubscriptionStatics = {};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Subscription = mongoose.model<SubscriptionDocument, SubscriptionModel>("Subscription", SubscriptionSchema);
 * ```
 */
export type SubscriptionModel = mongoose.Model<
  SubscriptionDocument,
  SubscriptionQueries
> &
  SubscriptionStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new Subscription schema instances:
 * ```
 * const SubscriptionSchema: SubscriptionSchema = new mongoose.Schema({ ... })
 * ```
 */
export type SubscriptionSchema = mongoose.Schema<
  SubscriptionDocument,
  SubscriptionModel,
  SubscriptionMethods,
  SubscriptionQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Subscription = mongoose.model<SubscriptionDocument, SubscriptionModel>("Subscription", SubscriptionSchema);
 * ```
 */
export type SubscriptionDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  SubscriptionQueries
> &
  SubscriptionMethods & {
    subscriber: UserDocument["_id"] | UserDocument;
    channel: UserDocument["_id"] | UserDocument;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of TweetDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `TweetDocument.toObject()`. To avoid conflicts with model names, use the type alias `TweetObject`.
 * ```
 * const tweetObject = tweet.toObject();
 * ```
 */
export type Tweet = {
  content: string;
  owner: User["_id"] | User;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of TweetDocument (type alias of `Tweet`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Tweet } from "../models"
 * import { TweetObject } from "../interfaces/mongoose.gen.ts"
 *
 * const tweetObject: TweetObject = tweet.toObject();
 * ```
 */
export type TweetObject = Tweet;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type TweetQuery = mongoose.Query<any, TweetDocument, TweetQueries> &
  TweetQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `TweetSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type TweetQueries = {};

export type TweetMethods = {};

export type TweetStatics = {};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Tweet = mongoose.model<TweetDocument, TweetModel>("Tweet", TweetSchema);
 * ```
 */
export type TweetModel = mongoose.Model<TweetDocument, TweetQueries> &
  TweetStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new Tweet schema instances:
 * ```
 * const TweetSchema: TweetSchema = new mongoose.Schema({ ... })
 * ```
 */
export type TweetSchema = mongoose.Schema<
  TweetDocument,
  TweetModel,
  TweetMethods,
  TweetQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Tweet = mongoose.model<TweetDocument, TweetModel>("Tweet", TweetSchema);
 * ```
 */
export type TweetDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  TweetQueries
> &
  TweetMethods & {
    content: string;
    owner: UserDocument["_id"] | UserDocument;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of UserDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `UserDocument.toObject()`. To avoid conflicts with model names, use the type alias `UserObject`.
 * ```
 * const userObject = user.toObject();
 * ```
 */
export type User = {
  username: string;
  email: string;
  password: string;
  fullName: string;
  avatar: string;
  coverImage?: string;
  refreshToken?: string;
  watchHistory: (Video["_id"] | Video)[];
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of UserDocument (type alias of `User`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { User } from "../models"
 * import { UserObject } from "../interfaces/mongoose.gen.ts"
 *
 * const userObject: UserObject = user.toObject();
 * ```
 */
export type UserObject = User;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type UserQuery = mongoose.Query<any, UserDocument, UserQueries> &
  UserQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `UserSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type UserQueries = {};

export type UserMethods = {
  isPasswordValid: (this: UserDocument, ...args: any[]) => any;
  generateAccessToken: (this: UserDocument, ...args: any[]) => any;
  generateRefreshToken: (this: UserDocument, ...args: any[]) => any;
};

export type UserStatics = {};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const User = mongoose.model<UserDocument, UserModel>("User", UserSchema);
 * ```
 */
export type UserModel = mongoose.Model<UserDocument, UserQueries> & UserStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new User schema instances:
 * ```
 * const UserSchema: UserSchema = new mongoose.Schema({ ... })
 * ```
 */
export type UserSchema = mongoose.Schema<
  UserDocument,
  UserModel,
  UserMethods,
  UserQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const User = mongoose.model<UserDocument, UserModel>("User", UserSchema);
 * ```
 */
export type UserDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  UserQueries
> &
  UserMethods & {
    username: string;
    email: string;
    password: string;
    fullName: string;
    avatar: string;
    coverImage?: string;
    refreshToken?: string;
    watchHistory: mongoose.Types.Array<VideoDocument["_id"] | VideoDocument>;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Lean version of VideoDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `VideoDocument.toObject()`. To avoid conflicts with model names, use the type alias `VideoObject`.
 * ```
 * const videoObject = video.toObject();
 * ```
 */
export type Video = {
  title: string;
  description: string;
  views?: number;
  duration: number;
  isPublished?: boolean;
  owner: User["_id"] | User;
  thumbnail: string;
  videoFile: string;
  _id: mongoose.Types.ObjectId;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Lean version of VideoDocument (type alias of `Video`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Video } from "../models"
 * import { VideoObject } from "../interfaces/mongoose.gen.ts"
 *
 * const videoObject: VideoObject = video.toObject();
 * ```
 */
export type VideoObject = Video;

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type VideoQuery = mongoose.Query<any, VideoDocument, VideoQueries> &
  VideoQueries;

/**
 * Mongoose Query helper types
 *
 * This type represents `VideoSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type VideoQueries = {};

export type VideoMethods = {};

export type VideoStatics = {
  aggregatePaginate: (this: VideoModel, ...args: any[]) => any;
};

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Video = mongoose.model<VideoDocument, VideoModel>("Video", VideoSchema);
 * ```
 */
export type VideoModel = mongoose.Model<VideoDocument, VideoQueries> &
  VideoStatics;

/**
 * Mongoose Schema type
 *
 * Assign this type to new Video schema instances:
 * ```
 * const VideoSchema: VideoSchema = new mongoose.Schema({ ... })
 * ```
 */
export type VideoSchema = mongoose.Schema<
  VideoDocument,
  VideoModel,
  VideoMethods,
  VideoQueries
>;

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Video = mongoose.model<VideoDocument, VideoModel>("Video", VideoSchema);
 * ```
 */
export type VideoDocument = mongoose.Document<
  mongoose.Types.ObjectId,
  VideoQueries
> &
  VideoMethods & {
    title: string;
    description: string;
    views?: number;
    duration: number;
    isPublished?: boolean;
    owner: UserDocument["_id"] | UserDocument;
    thumbnail: string;
    videoFile: string;
    _id: mongoose.Types.ObjectId;
    createdAt?: Date;
    updatedAt?: Date;
  };

/**
 * Check if a property on a document is populated:
 * ```
 * import { IsPopulated } from "../interfaces/mongoose.gen.ts"
 *
 * if (IsPopulated<UserDocument["bestFriend"]>) { ... }
 * ```
 */
export function IsPopulated<T>(doc: T | mongoose.Types.ObjectId): doc is T {
  return doc instanceof mongoose.Document;
}

/**
 * Helper type used by `PopulatedDocument`. Returns the parent property of a string
 * representing a nested property (i.e. `friend.user` -> `friend`)
 */
type ParentProperty<T> = T extends `${infer P}.${string}` ? P : never;

/**
 * Helper type used by `PopulatedDocument`. Returns the child property of a string
 * representing a nested property (i.e. `friend.user` -> `user`).
 */
type ChildProperty<T> = T extends `${string}.${infer C}` ? C : never;

/**
 * Helper type used by `PopulatedDocument`. Removes the `ObjectId` from the general union type generated
 * for ref documents (i.e. `mongoose.Types.ObjectId | UserDocument` -> `UserDocument`)
 */
type PopulatedProperty<Root, T extends keyof Root> = Omit<Root, T> & {
  [ref in T]: Root[T] extends mongoose.Types.Array<infer U>
    ? mongoose.Types.Array<Exclude<U, mongoose.Types.ObjectId>>
    : Exclude<Root[T], mongoose.Types.ObjectId>;
};

/**
 * Populate properties on a document type:
 * ```
 * import { PopulatedDocument } from "../interfaces/mongoose.gen.ts"
 *
 * function example(user: PopulatedDocument<UserDocument, "bestFriend">) {
 *   console.log(user.bestFriend._id) // typescript knows this is populated
 * }
 * ```
 */
export type PopulatedDocument<DocType, T> = T extends keyof DocType
  ? PopulatedProperty<DocType, T>
  : ParentProperty<T> extends keyof DocType
  ? Omit<DocType, ParentProperty<T>> & {
      [ref in ParentProperty<T>]: DocType[ParentProperty<T>] extends mongoose.Types.Array<
        infer U
      >
        ? mongoose.Types.Array<
            ChildProperty<T> extends keyof U
              ? PopulatedProperty<U, ChildProperty<T>>
              : PopulatedDocument<U, ChildProperty<T>>
          >
        : ChildProperty<T> extends keyof DocType[ParentProperty<T>]
        ? PopulatedProperty<DocType[ParentProperty<T>], ChildProperty<T>>
        : PopulatedDocument<DocType[ParentProperty<T>], ChildProperty<T>>;
    }
  : DocType;

/**
 * Helper types used by the populate overloads
 */
type Unarray<T> = T extends Array<infer U> ? U : T;
type Modify<T, R> = Omit<T, keyof R> & R;

/**
 * Augment mongoose with Query.populate overloads
 */
declare module "mongoose" {
  interface Query<ResultType, DocType, THelpers = {}> {
    populate<T extends string>(
      path: T,
      select?: string | any,
      model?: string | Model<any, THelpers>,
      match?: any
    ): Query<
      ResultType extends Array<DocType>
        ? Array<PopulatedDocument<Unarray<ResultType>, T>>
        : ResultType extends DocType
        ? PopulatedDocument<Unarray<ResultType>, T>
        : ResultType,
      DocType,
      THelpers
    > &
      THelpers;

    populate<T extends string>(
      options: Modify<PopulateOptions, { path: T }> | Array<PopulateOptions>
    ): Query<
      ResultType extends Array<DocType>
        ? Array<PopulatedDocument<Unarray<ResultType>, T>>
        : ResultType extends DocType
        ? PopulatedDocument<Unarray<ResultType>, T>
        : ResultType,
      DocType,
      THelpers
    > &
      THelpers;
  }
}
